import { cn } from '../../utils/cn.js';
import { Reveal } from '../ui/Reveal.jsx';
import { goals } from '../../data/goals.js';

/* The register of adopted goals.

   Numbered because the goals were adopted as a numbered list — the
   numeral is the reference, not decoration, so it is printed rather than
   generated by a list-style. Set in two columns that break cleanly. */
export function GoalRegister({ showPillar = false, className }) {
  return (
    <Reveal
      as="ol"
      className={cn('columns-[22rem_2] gap-x-[clamp(2rem,6vw,5rem)]', className)}
    >
      {goals.map((goal) => (
        <li
          key={goal.no}
          className="grid break-inside-avoid grid-cols-[3.1rem_1fr] items-baseline gap-[0.6rem] border-b border-gold-ink/20 py-[0.95rem]"
        >
          <span className="font-mono text-note font-medium tracking-[0.08em] text-gold-ink">
            {goal.no}
          </span>

          <span className="font-voice text-lead leading-[1.35] text-ink-text">
            {goal.name}
            {showPillar && (
              <>
                <br />
                <small className="font-mono text-meta tracking-[0.06em] text-gold-ink">
                  {goal.pillar}
                </small>
              </>
            )}
          </span>
        </li>
      ))}
    </Reveal>
  );
}
